### ISSUE TITLE
Bug: max-height property doesn't seem to work in IE 

### ISSUE THREAD

**Issue by aartiD** [isteven/angular-multi-select#153]
In IE the max-height property of multi-select does not work. when a huge no of items are bound to multiselect dropdown it overflows the IE page  and to view more items we have to use arrow key but in that case the main multi-select control runs out of the view. 

Also selecting a item in multi-select on IE browser , when the focus is on the selected item item content is not displayed

**Comment by broguyman** [comment]
You also need to add the overflow-y: scroll; to the inline style in the line mentioned above by isteven.

Just so that I would have to manipulate the directive I added the following css and added the multi-div class to the div where the multi select is created. This way you can specify which multi select has the max-height and scrolling. If you add the style directly to the directive it will be applied to all multiselects in the app.  

.multi-div .checkBoxContainer {
    max-height: 220px;
    overflow-y: scroll;
}

I tried changing the style in the directive to ng-style and I couldn't get it to work but with ng-style at least the setHeight() function was being called. The setHeight() method doesn't get called in the style attribute with IE.

**Comment by isteven** [comment]
@broguyman 

Thanks for the update, much appreciated :)

**Comment by NalinSajwan** [comment]
Hi @isteven,
In which version is this fix available ? I am at v2.0.2 and issue is still available on IE 11.

**Comment by isteven** [comment]
@NalinSajwan 

Try to download the latest version (v4.0.0). If it doesn't work, set it manually by following these 2 steps:  https://github.com/isteven/angular-multi-select/issues/153#issuecomment-67101299 and https://github.com/isteven/angular-multi-select/issues/153#issuecomment-68712377
