### ISSUE TITLE
IE8 & IE9 (Background turning white on hover)

### ISSUE THREAD

**Issue by johneakin** [isteven/angular-multi-select#163]
Hi,
I am having a problem with IE8 and IE9
When the mouse is hovered over an item in the dropdown the hovered over entry all turns white (including the text for that item)

Is there any way to resolve this?

**Comment by isteven** [comment]
Hi @johneakin , 

For IE8, please download the release version 1.2.0.

**Comment by nabinca** [comment]
This should be reopened because it also occurs in IE9.

**Comment by isteven** [comment]
Hi @nabinca , 

Can you please reproduce the issue in JsFiddler or Plunker?

**Comment by nabinca** [comment]
Hi, sorry I'm currently under great pressure.

Adding a background-color: #999 
to
.multiSelect .multiSelectItem:hover, .multiSelect .multiSelectGroup:hover

solved the issue. I'm not a CSS-guru. I think the problem is that IE9 doesn't support linear gradients and displays a white background instead. The text on hover is also white, so the items cannot be seen.

No Plunker needed, you can reproduce it with the demo page. On hover, the Browser names can't be read.

**Comment by isteven** [comment]
Thanks a lot for the advice, @nabinca.

May I know which version you are using? The current demo page uses v4.0.0, which, I believe, only supports IE10 and above. 

Also, unfortunately I only have IE11 with me at the moment, so there's no way I can test it myself.

**Comment by nabinca** [comment]
We are currently using version 3.0.0, and it works fine in IE9.
I also just have IE11, but you can switch to IE9-compatiblity mode to reproduce.
Open the dev tab (F12 in IE) and there you can select IE9-compatibility-mode by clicking on 'Edge' on the right side of the panel. As long as the dev tab is open, you see the page like it would be in IE9, If you close the dev tools the browser switches back to actual version.

**Comment by isteven** [comment]
Thanks for the help, @nabinca. 

I'm not able to do a fix at the moment. Currently busy with stuffs. Will update these later.

**Comment by bluee** [comment]
Compatibility mode is not always rendering correct. Rather download a virtual image from here to test with a true IE9

https://dev.windows.com/en-us/microsoft-edge/tools/vms/mac/
