### ISSUE TITLE
Globally declared variables

### ISSUE THREAD

**Issue by RichLinnell** [isteven/angular-multi-select#180]
Can I ask why in the link function there are three items that are not defined at the $scope level? The last three in the snippet below.

This is causing clashes.

```javascript
        link: function ( $scope, element, attrs ) {           

            $scope.backUp           = [];
            $scope.varButtonLabel   = '';   
            $scope.scrolled         = false;
            $scope.spacingProperty  = '';
            $scope.indexProperty    = '';            
            $scope.checkBoxLayer    = '';
            $scope.orientationH     = false;
            $scope.orientationV     = true;
            $scope.filteredModel    = [];
            $scope.inputLabel       = { labelFilter: '' };
            $scope.selectedItems    = [];                                    
            $scope.formElements     = [];
            $scope.tabIndex         = 0;
            $scope.clickedItem      = null;
            prevTabIndex            = 0;
            helperItems             = [];
            helperItemsLength       = 0; 
```

**Comment by isteven** [comment]
Hi @RichLinnell , 

Not all variables/functions have to be declared in the $scope. In fact, usually developers will try to put as little stuff as possible into the $scope.

This is just a guess, but the problem happens because I didn't use strict mode to code this (version 3.0.0 is strict). Usually it will also trigger some errors if you try to minify the code.

The workaround is to declare 'use strict' at the beginning of the code, and use explicit variable declaration, such as:

var prevTabIndex = 0; 
var helperItems = [];
var helperItemsLength = 0;

There might be other functions need declaration as well. Just add them and you're good to go.

Hope this helps.

**Comment by RichLinnell** [comment]
yeah, it was WebEssentials bundle/minification that was causing the blowout.  I just excluded the file for now.  I'll try out the strict mode when I have some spare time.
