### ISSUE TITLE
Does it work under an ngRepeat?

### ISSUE THREAD

**Issue by GregTD42** [isteven/angular-multi-select#191]
tr ng-repeat = "user in userStores">
td
    div multi-select input-model = "user.storeChoices" button-label = "store" item-label = "store" tick-property="ticked"  /div
/td
I have multiple users, each one has a "storeChoices" array.  Nothing at all is displaying.  Should this work?

**Comment by isteven** [comment]
Hi @GregTD42 ,

Thanks for informing this. Can you replicate the problem in Plunker or JsFiddler so I can have a look?

**Comment by GregTD42** [comment]
Hi Steven,

Turns out the problem was me, I hadn't saved a code change I needed for it to work.

However, with 12 of these, four text elements each, I'm not getting it to respond to a select click (i.e. the menu opens, but selecting one of the choices doesn't do anything).

Putting 70 of these on a page pretty much kills Chrome.  Is that expected?  What are your expected performance levels?  IOW, how many of these should I be able to put on a page?

Thank you.

**Comment by isteven** [comment]
Hi @GregTD42 , 

Admittedly it was never designed for performance (I put this clearly on the manual page). If you read the old issues, some people had problem with large selection items (1000+ items in the selection). No one ever mentioned it kill the browser, though.  

This is just an advice, but I suggest you to modify your form flow. I can imagine some human errors happening because of 70 multi select elements in one page (I assume it's on the same page). Dynamically hidden/displayed elements will make it even worse.

Anyway, to check on this issue (and the non-responding problem on clicking), I guess I need to look at the code - a plunker or fiddler would be nice.
