### ISSUE TITLE
v3.0.0 is up!

### ISSUE THREAD

**Issue by isteven** [isteven/angular-multi-select#194]
Hi all, 

It's been more than a year since I started this directive project, and with that I'm glad to announce version 3.0.0 of this directive.

Changes for v3.0.0:  
- Support for AngularJs version 1.3.x (v3.0.0 also supports AngularJs 1.2.x, but beware of the breaking changes)
- Customized text on helper elements
- 5 new callbacks
- You can now set minimum characters required to trigger the search functionality
- You can now define which input-model properties to search from (previously, all input-model properties are searched)
- On close, parent button will now receive focus.
- Limited support on promise objects.
- Various small optimizations.

Still on progress for next release:
- Using strict mode Lazy loading (checkbox DOMs won't be generated before you start filtering. Hopefully will help to increase performance on big model) 
- AJAX input
- Fully customized button and item labels (I have the logic ready, but not sure whether many people need this, as this is going to be another breaking changes) 

You now have a new demo & manual page, which is, IMO, much better than the old one. 

I am also creating a donation button.. Moving away from my full time job, so it's always nice to see some financial helps coming in :)

Thanks and enjoy!

**Comment by martybalandis** [comment]
bring back "default-label". In version 2 i was able to set something: 
data-default-label="<img src='http://my.{{valuex}}.website.com/images/{{form.image}}'> {{form.image}}"
now i am forced to do it in translation which is not ready in time. If I set it to something and then try to change it it doesn't update anymore. 

Example: 


Also, search bar clear button is broken (displays Ã— instead of icon)

**Comment by martybalandis** [comment]
bring back "default-label". In version 2 i was able to set something:

default-label="img src='http://my.{{valuex}}.website.com/images/{{form.image}}'> {{form.image}}" 

now i am forced to do it in translation which is not ready in time. If I set it to "" and then try to change it it doesn't update anymore.

Example:
        $scope.imageSelectTranslation = {
            nothingSelected : "Nothing is selected"
        };

        $timeout(function () {
            $scope.imageSelectTranslation = {
                nothingSelected : "<img src='http://my.'" + $rootScope.valuex + '.website.com/images/' + $scope.form.image
            };
        });

I would be fine if the above worked but it doesn't.
Version 3 made it not possible or a lot harder to set the selection in advance.
Also, search bar clear button is broken (displays Ã— instead of icon)

Any ideas how I can do this?

**Comment by martybalandis** [comment]
Found a workaround do you know why it shows Ã— instead of X?

**Comment by jptannus** [comment]
Great stuff! :D

**Comment by isteven** [comment]
@jptannus 

Thanks!

**Comment by isteven** [comment]
Guys n girls, fellow developers..

Apparently I've done a big mistake here.. v3.0.0 introduces a bug when you deal with granular data (for example, dynamically disabling a data, or, modifying a data). This happens because I tried to "isolate" input-model (to make it reusable). As a result, for now you can't do any granular data operation.

I'm working to fix that (along with other bug fixes), but most likely I can't keep the input-model isolated. After the fix, the input-model behaviour will be similar to version 2.x.x.

Really sorry for this.
