### ISSUE TITLE
Why is this an Angular directive?

### ISSUE THREAD

**Issue by ed-at-work** [isteven/angular-multi-select#204]
This is more of a question than anything else. This is one of the better multi-selects out there that uses Angular, but I don't understand why you are using the input-model and the output-model at all?   It's like you've completely missed the point regarding Angular's data-binding, which is really part of the raison d'être of Angular.  Nothing is more annoying as a user of libraries on Github to find a decent one that completely missed the point of Angular.

**Comment by isteven** [comment]
Hi @ed-at-work , 

Well some reasons.. But please tell me, in your opinion, the Angular way of doing this is...?

**Comment by mtheoryx** [comment]
Should this really be an issue here? Perhaps an email thread on philosophy of use would be more productive.

As far as I can tell, the inputmodel and outputmodel take advantage of AngularJS strengths, and this directive is following good practices.

/my two cents, using this directive extensively in production

**Comment by isteven** [comment]
@mtheoryx , 

Haha nevermind mate, I enjoy this kind of philosophical questions.. Well at least after replying to technical questions I see almost everyday, you'll find this like water in the desert LOL.

**Comment by brandonhesse** [comment]
Just my two cents on this, while I think the input and output models are perfectly fine, I'm guessing that @ed-at-work  would want it to look like the syntax for:
ngOptions or ngRepeat, where you simply provide a string and it parses the input-output model from that.

From this:

```html
    <div isteven-multi-select
        input-model="modernBrowsers"
        output-model="outputBrowsers"
        button-label="icon name"
        item-label="icon name maker"
        tick-property="ticked"
    ></div>
```

To this:
```html
     <div data-isteven-multi-select="browser as browser|formatter for browser track by browser.name in modernBrowsers" data-tick-property="ticked" data-item-label="icon name maker" data-button-label="icon name">
   <!-- Maybe children directives? -->
</div>
```

But PERSONALLY, I think that the methods provided are perfect as is, and this has to be the best multiselect me and my associates have seen, correctly using input:checkbox over <div> and <span> elements.

**Comment by isteven** [comment]
Hi @brandonhesse , 

Thanks for the response. I'm guessing the same - it's more or less what @ed-at-work meant: using ng-options/ng-repeat, and/or children directive instead of pure HTML DOMs. Let's look at it one by one as I share my thoughts and explain the situation behind the directive's design decision

##### ng-options 

AngularJs' [ng-options documentation] (https://docs.angularjs.org/api/ng/directive/ngOptions) states that ng-options is used to generate <code>&lt;option&gt;...&lt;/option&gt;</code> list for <code>&lt;select&gt;</code> tag. Now the thing is, this directive does not use <code>&lt;select&gt;</code> tag. It's too restrictive for what I want to achieve, hence the <code>divs</code> and <code>spans</code> I use instead.

Also, this is personal, but IMHO <code>ng-options</code> is like a bad counterfeit of SQL <code>SELECT</code> query (Sorry AngularJs team - please don't take it personally).

##### ng-repeat (and children directives)

On the other hand, I like <code>ng-repeat</code>. Even newbie developers know how it works and what it is trying to achieve just by looking at the <code>ng-repeat</code> statement (at least in it's basic form). Of course, you can easily guess that I do use ng-repeat in this directive.

Now the question is why I don't use let users use ng-repeat and define their own children directives as you said above. There reasons:

1. Technically, I found it quite difficult to provide keyboard support and grouping using children directive. Perhaps my skill is not yet there.
2. You will end up cluttering your HTML file even more. I believe, *ideally*, a directive declaration should be a one liner. I prefer to have a properly written input-model. In the *form-follows-function* way of thinking that I firmly believe, a good input model can describe your output.
3. I believe there'll be performance hit somewhere as you create more children directives. Just check earlier issues.

##### Others

I was new to AngularJs when I started this project. I often jokingly think that it's *the* bastard child of illegal relationship between deadline pressure and lack of skill.

Anyway yeah I'll just keep this open, hopefully @ed-at-work can reply & explain his thoughts as well.

**Comment by isteven** [comment]
Turns out that this is just a fire-and-forget post from original poster. 

Am closing it. Cheers.

**Comment by brandonhesse** [comment]
I don't believe I meant to fire and forget. I still would like this problem solved, but when you said you'd be supporting it, I didn't think it was worth further pushing buttons.

I tend not to create spam posts like "Thanks" and "When will this be done?"

because I understand that even the simplest of changes require development time.

**Comment by ShawnStrickland** [comment]
I get what he's saying here...

For instance I have a project that doesn't use native form controls.  At all.  Everything is custom which has led me to your repo.  This is a very nice directive.

In my project there's an admin screen that at once point has a select and multi-select.  However I need to be able to bind these selects to an array of available "seasons" and the data that's corresponding on the page.

    $scope.seasons = [
      { name: 'Early Pre-Season' },
      { name: 'Pre-Season' },
      { name: 'Late Season' }
    ];

    $scope.campaigns = [
      {
        name: 'Campaign 1',
        overview: 'Campaign 1 overview',
        desc: 'Campaign 1 description',
        seasons: [
          {
            name: 'Early Pre-Season'
          },
          {
            name: 'Late Season'
          }
        ]
      }...
    ];

In the HMTL I can easily accomplish this with correct data-binding both ways using:

    <select
       multiple
       ng-model="selectedCampaign.seasons"
       ng-change="addOrUpdateRecord('update', 'seasons', selectedSeasons)"
       ng-options="season.name for season in seasons track by season.name
     ></select>

The alternative, like you have set up in your `input-model` object would require a lot of extra logic to keep everything in sync.

Enabling this "track by" logic (as I see it anyway) to be more like a native select with ng-options would make this directive a staple in every project I do.

Great work either way, @isteven, thanks!
