### ISSUE TITLE
need IE8 support

### ISSUE THREAD

**Issue by madasuk** [isteven/angular-multi-select#211]
As most of our customers use IE8, I need to make this multi-select dropdown to work on IE8. What I need to do make it work in IE8, is it possible? Currently when I try to use it in IE8, it is not the displaying dropdown?

**Comment by isteven** [comment]
Hi,

Go to the releases page and download release v1.2.0.

**Comment by madasuk** [comment]
Thanks isteven, but when I read the release notes of v2.0.0 and the later, I realized there are lot many fixes and features are provided. Now if I use v1.2.0, I may be losing all these fixes and features and fearing about the stability of it  in  our production release . Is there any possibility to make the current release v.3.0.0 compatible with IE8,  as still many people are using and requesting IE8 support?

**Comment by tedyoung** [comment]
I'm gonna vote -1 for this. There's a reason IE 8 is losing support in various tools and components: because it's really hard to retain compatibility, which means new, more useful features wouldn't get attention.

I work for an enterprise software company that sells on-premises software to large companies, and even we have finally stopped supporting IE8.

**Comment by starforgelabs** [comment]
I agree with tedyoung and downvote also. I just looked up IE8 use globally, and it's rare these days (2%) and declining.  

Though I find "As most of our customers use IE8" an interesting statement. More than half of your customers use IE8? I'm not doubting you as I don't know your area of specialization. 

This implies that it's a tight niche market that relies on old versions on Windows. I'm familiar with this type of niche and am involved with supporting old software on such a niche. Saying that, I'm completely sympathetic with your quandry. 

If you've been using this library already, you can do a binary (half-interval) search strategy to quickly find which commit breaks IE8 support. That will give you the ability to evaluate whether that version suffices, whether fixing the break in IE8 support is an easy fix, whether it's worth it to branch, or some other option. I've had to do similar things with the project I provide support for. (Fortunately it's only a few times a year.) 

I'm merely throwing out ideas in an attempt to be helpful while maintaining my opinion that it's not worth the resources to retain IE8 support.

**Comment by madasuk** [comment]
Thanks @starforgelabs, I agree with your valuable feed back.  Our statistics shows nearly 25% of the sessions are of IE8 and these are from our most important customers. My statement  "As most of our customers use IE8" gives wrong meaning to what I wanted to indicate sorry for that. After investigation, now I realized IE8 has some major security vulnerabilities which Microsoft is not going to fix. So I will rethink the decision of supporting to IE8 to our clients. For now this issue can be closed. Thanks to all.

**Comment by starforgelabs** [comment]
While 25% is not most, it's a significant percentage and in your shoes it's a valid question to raise. 

Best wishes.

**Comment by isteven** [comment]
Just want to share a bit; 

I work in financial and banking industry, and my apps are used internally by colleagues through local network, so yeah about 95% of the traffic is IE8 (Of course, it's small in absolute number compared with the all users in the world).

The reason we stick with IE8 is because, for us, it is better to use the default browser coming from the default official OS (Win 7 & IE8), as this allows us and our IT hardware vendor to manage things better and minimize risk. More variations = more challenges when sh*t happens = more time needed to fix etc. So they like things to be "standard", and usually that means sticking with just whatever default technologies available.

I am sure there are a lot of people in similar situation, so the question is indeed valid - but I prefer to move forward here (not to mention that newer versions of popular libraries like Bootstrap and AngularJs etc will also remove support for IE8).
