### ISSUE TITLE
How could we call to the $scope.select function inside the callback functions (on-select-all, on-select-none, ...)?

### ISSUE THREAD

**Issue by danicomas** [isteven/angular-multi-select#336]
I would like has only one button to select or unselect items. I tried to edit the template and I tried to call inside the following callbacks but I didn't find the way:

```js
on-select-all="fSelectAll()"
on-select-none="fSelectNone()"
on-reset="fReset()"
on-clear="fClear()"
```

Probably we would need one of the next things:
- Pass the directive $scope in the callback (the scope has the select function)
- Creating some button inside the directive
- Pass the $event in the callback?

**Comment by isteven** [comment]
Hi @danicomas , 

Unfortunately there's no such option - you'll need to modify things yourself.

Since you tried to edit the template, I can say that you're on the right direction. Create a button to directly modify the input-model. Just loop over the input-model, and set the selected property to true.

The directive's $watch-ers should then proceed with the rest.
