### ISSUE TITLE
Nested multi-select problem

### ISSUE THREAD

**Issue by hborisov1** [isteven/angular-multi-select#354]
Hello. 

I have an isteven-multi-select box and I want to use it's output values as an input to another multi-select boxes. Here is the example code: http://plnkr.co/edit/0jca6nGOvC6Efo2ZcflF?p=preview

Frirst I make a selection in the parent box and after that in the child boxes, but when I change the parent box again - the output values of the remaining child boxes are cleared. 

Am I doing something wrong?

**Comment by isteven** [comment]
@hborisov1,

Unfortunately you're not doing anything wrong - it's simply the behaviour of the directive. The output-model is refreshed everytime you select / deselect an item.

When you select / deselect an item from your parent directive, the parent's output-model is re-build from scratch. That's why the child's input-model is always new.

I think you can use some sort of a temporary / holding variable for this case.

**Comment by hborisov1** [comment]
Thanks for the response. 

I solved the problem as you suggested: on every item click in the parent, I update an output array (which is NOT the parent output) and then I use it as an input to the children.

I updated the plnkr example.
