### ISSUE TITLE
How can I add a keypress event that selects current item and closes select box?

### ISSUE THREAD

**Issue by HollandRisley** [isteven/angular-multi-select#369]
I would like the Return key to select the currently selected item and close the select box. 
I tried adding this at line 1088:

'ng-keyup="if($event.which === 13) syncItems( item, $event, $index )"' +

But I can't get this to trigger..

Any ideas on how  I can do this?

**Comment by HollandRisley** [comment]
Further to this I just noticed that actually space bar already does exactly what I want! 

So I would like to change the Keypress Id that triggers the save and close event from Space Bar to the Return key.

Also I would like to add the down arrow to the list of keys that activate the control. When tabbing from the previous field, I would like to click down arrow to open this, currently the return key does this job.

So can you point me in the right direction of changing these keycodes? I have tried searching through the code and I can't find the Spacebar or Return key events anywhere..! :)

**Comment by isteven** [comment]
Hi, 

I actually try to rely on whatever default browser implementation for most of the things. That's why you don't see return or spacebar keys (13 or 32) keys in the code. 

For example, since it's actually just a button, pressing return or spacebar on the button will toggle the dropdown.

Another example is on the selection item. I actually use a checkbox to handle the keyboard listener, so spacebar will select/deselect an item.

I personally against the down arrow to activate the control since it's not a standard, but if you need it, you'll need to add your own key listener. Just add new keys in the <code>keyboardListener</code> function.
