### ISSUE TITLE
How to set required field for Validation

### ISSUE THREAD

**Issue by AhamedSKR** [isteven/angular-multi-select#38]
How to set required field for Validation

**Comment by BobbieBarker** [comment]
You keep handing out the same piece of advise over and over again about inquiries related to form validation and your answer is really a cop out for not supporting something that should be supported. While you could easily argue that custom or exotic business logic should be handled by the user of your directive you should be exposing an attribute that would allow the user to make the directive required.

**Comment by isteven** [comment]
@BobbieBarker , 

There are really various ways of validating form elements, and there's no way I can support all. This project initially started because of work requirement, and, at that time, the only validation I required was before submitting the form. This was easily done without the need of exposed attributes or methods. 

I do hope you & everyone else understand that I have no obligation to work on any extra feature in the directive. As fellow Github members, I believe the better thing you can do is to fork & customise things to suit your requirements.

**Comment by evivz** [comment]
@BobbieBarker  I found one better method on stackoverflow: http://stackoverflow.com/a/29310019/1500341

Which worked for me at least.

**Comment by prudhvi-php** [comment]
how can i get the selected items in controller ?
