### ISSUE TITLE
Mixing angular-multi-select with angular-formly

### ISSUE THREAD

**Issue by estvmachine** [isteven/angular-multi-select#384]
Hi, im trying using both plugins in my project (http://angular-formly.com/#/), actually with sucess, but i need to ask certain questions. But first goes first, im trying to do a jsbin, but not work very well, can you help me with that?

http://jsbin.com/bipoze/12

http://jsbin.com/bipoze/12/edit?html,js

**Comment by isteven** [comment]
@estvmachine,

Unfortunately I have zero experience in angular-formly. 

I can only inform you few things;

1. You better use CDNJS instead of Github. We have one here but I haven't got chance to update the manual; 
 - https://cdnjs.cloudflare.com/ajax/libs/angular-multi-select/4.0.0/isteven-multi-select.css
 - https://cdnjs.cloudflare.com/ajax/libs/angular-multi-select/4.0.0/isteven-multi-select.js

2. You define "icon" in the "button-label" and "item-label", but I didn't see "icon" property in your vm.names object.

3. Likewise, you use "ticked" in the "tick-property", but I didn't see "ticked" property in your vm.names object. You need to add them.

4. For the translation attribute, you need to define the translation object in the controller.

**Comment by estvmachine** [comment]
Hi, i check your suggestions and now its working:

http://jsbin.com/vayafi/5

Well, i actually make the merge successfull, thank you!

**Comment by isteven** [comment]
You're welcome, glad can help. 

I'll be closing the issue now. Cheers.

**Comment by estvmachine** [comment]
Yeah you're welcome, thanks, i love this plugin.
