### ISSUE TITLE
Support for ng-model directive

### ISSUE THREAD

**Issue by jibusayone** [isteven/angular-multi-select#455]
I have a list of values inside a list, which is the input-model. But to prepopulate the selected ones on page load, I had to loop over the services and mark 'ticked' = true for all matching list entities. Here is what I did:

```
angular.forEach($scope.services, function (service) {
    angular.forEach($scope.place.services, function (value) {
        if (service.id == value.id) {
            service['ticked'] = true;
        }
    });
});
```

Is this how we should manage the problem? Or you could provide support for ng-model directive too, right? Cheers.

**Comment by isteven** [comment]
@jibusayone , 

Unfortunately that is correct. That's how you do it with the input-model.

The reason is; 
- ng-model, (by default) deals with HTML's input element. This directive, unfortunately, does not really utilize HTML input element.
- the reset functionality requires me to separate the input and output.
- and this is just me, but i believe that, a software, from the top (say, a directive) down to its simplest core (say, functions or methods), simply do one thing: process input into output - hence the name.
