### ISSUE TITLE
Max rows displayed option

### ISSUE THREAD

**Issue by tim-lukacik** [isteven/angular-multi-select#459]
Why not solve performance issues on large result sets by adding a max rows displayed attribute? I added this, put a limitTo filter on the repeat for the results display, and put a "Display first X rows" at the bottom with a ng-if checking if the filteredresults length is > the max rows.

The search function still works this way and now the enormous lag (I have ~5k records sometimes) is completely gone. The code is very minimal, but I can create a pull request if you'd like. 

Thank you for this excellent control!

**Comment by isteven** [comment]
@tim-lukacik 

Tim, a pull request would be appreciated. Just make sure it works will all the features (grouping, filtering, select all, none, reset, etc).

**Comment by Wingie** [comment]
Yes, im also facing a lot of performance issues with this control..
could you share your code?

**Comment by tim-lukacik** [comment]
@Wingie Take a look at #460. I found a limit of 500 to work acceptably on my machine so I suggested that as default. Seems to work with everything. It's just limiting what's displayed, not actually touching any arrays. It could potentially cause a group to not be fully listed if the group happens to be around the limit.

**Comment by tim-lukacik** [comment]
A better solution would be pagination here instead :)

**Comment by Wingie** [comment]
Or maybe a solution that involved "virtual rows" or something.. like
writing only the visible elements to the DOM.. because from what i'm seeing
the issue is the angular double binding and large number of watchers.

i have the need to put multiple dynamically changing multiselects on a
single page..
and sometimes chrome gets stalled because of the performance issues.

[Wilson Wingston Sharon]

**Comment by tim-lukacik** [comment]
If you haven't already, check out ui-grid.
